# tasks file for ssh-keys
---
- name: authorized-keys | set up for users
  authorized_key:
    user: "{{ item.0.owner }}"
    key: "{{ lookup('file', item.1) }}"
    state: "{{ item.0.state | default('present') }}"
  with_subelements:
    - "{{ ssh_keys_authorized_keys }}"
    - src
  tags:
    ssh-keys-authorized-keys-setup
